/**
 * Retro-futurist neon and print/editorial themes. The print family is where hierarchy
 * comes from rules, weight and whitespace instead of filled boxes.
 */

export const RETRO_PRINT = [
    {
        slug: 'vaporwave-sunset',
        name: 'Vaporwave Sunset',
        family: 'retro',
        mode: 'dark',
        blurb: 'Pink to teal gradient with a horizon grid fading into the body.',
        surface: {
            headFrom: '#2b1055', headTo: '#ff2e93',
            bodyFrom: '#20124d', bodyTo: '#3b1c6b',
            row: 'rgba(255,255,255,0.07)', rowAlt: 'rgba(0,255,224,0.14)',
            inset: 'rgba(255,255,255,0.10)', chip: 'rgba(255,46,147,0.18)',
        },
        ink: {
            head: '#ffe6ff', body: '#eddcff', label: '#00ffe0', muted: '#a78ac8',
            strong: '#ffffff', warm: '#ffb86c', cool: '#00ffe0',
        },
        line: { head: 'rgba(0,255,224,0.45)', body: 'rgba(255,46,147,0.28)', width: '1px', edge: '3px' },
        shadow: { head: '0 8px 26px rgba(255,46,147,0.30)', body: 'none' },
        accents: ['#ff2e93', '#00ffe0', '#ffd700', '#8a2be2', '#ff6ec7', '#00b3ff', '#ff9a3c'],
        radius: { head: '6px', body: '6px', row: '5px', slot: '5px' },
        type: {
            family: '"Futura", "Century Gothic", ui-sans-serif, sans-serif',
            bodyFamily: 'inherit', headSize: '11px',
            headCase: 'uppercase', headTracking: '0.22em',
        },
        glyph: { section: '▲', sectionAlt: '△', bullet: '▸', sep: '◆', chevron: '▾' },
        extra: { body: 'background-image:repeating-linear-gradient(0deg,rgba(0,255,224,0.07) 0 1px,transparent 1px,transparent 14px),repeating-linear-gradient(90deg,rgba(0,255,224,0.07) 0 1px,transparent 1px,transparent 14px)' },
    },
    {
        slug: 'synthwave-drive',
        name: 'Synthwave Drive',
        family: 'retro',
        mode: 'dark',
        blurb: 'Indigo to magenta with a chrome-gradient header and a horizon rule.',
        surface: {
            headFrom: '#1a1040', headTo: '#c2185b',
            bodyFrom: '#150c33', bodyTo: '#241350',
            row: 'rgba(255,255,255,0.06)', rowAlt: 'rgba(255,110,199,0.14)',
            inset: 'rgba(255,255,255,0.09)', chip: 'rgba(255,110,199,0.16)',
        },
        ink: {
            head: '#ffd6f5', body: '#e4d9ff', label: '#ff6ec7', muted: '#9d8ac0',
            strong: '#ffffff', warm: '#ffab40', cool: '#4dd0e1',
        },
        line: { head: 'rgba(255,110,199,0.5)', body: 'rgba(255,110,199,0.26)', width: '1px', edge: '3px' },
        shadow: { head: '0 10px 28px rgba(194,24,91,0.34)', body: 'none' },
        accents: ['#ff6ec7', '#4dd0e1', '#ffab40', '#7c4dff', '#ff5252', '#69f0ae', '#ffd740'],
        radius: { head: '8px', body: '8px', row: '6px', slot: '6px' },
        type: {
            family: '"Eurostile", "Michroma", ui-sans-serif, sans-serif',
            bodyFamily: 'inherit', headSize: '11px',
            headCase: 'uppercase', headTracking: '0.14em', headWeight: '700',
        },
        glyph: { section: '◤', sectionAlt: '◥', bullet: '▸', sep: '/', chevron: '▾' },
        extra: { header: 'border-bottom:2px solid rgba(255,171,64,0.6)' },
    },
    {
        slug: 'arcade-cabinet',
        name: 'Arcade Cabinet',
        family: 'retro',
        mode: 'dark',
        blurb: 'CRT bezel highlight over saturated primaries.',
        surface: {
            headFrom: '#101010', headTo: 'rgba(255,215,0,0.18)',
            bodyFrom: '#0a0a0a', bodyTo: '#141414',
            row: 'rgba(255,255,255,0.06)', rowAlt: 'rgba(255,215,0,0.14)',
            inset: 'rgba(255,255,255,0.09)', chip: 'rgba(255,215,0,0.14)',
        },
        ink: {
            head: '#ffd700', body: '#f0f0f0', label: '#ff4136', muted: '#7a7a7a',
            strong: '#ffffff', warm: '#ffd700', cool: '#39cccc',
        },
        line: { head: 'rgba(255,215,0,0.5)', body: 'rgba(255,255,255,0.18)', width: '2px', edge: '4px' },
        shadow: { head: 'inset 0 2px 0 rgba(255,255,255,0.25), 0 8px 20px rgba(0,0,0,0.6)', body: 'none' },
        accents: ['#ffd700', '#ff4136', '#39cccc', '#2ecc40', '#b10dc9', '#ff851b', '#0074d9'],
        radius: { head: '4px', body: '4px', row: '3px', slot: '3px' },
        type: {
            family: '"Press Start 2P", ui-monospace, monospace',
            bodyFamily: 'ui-monospace, Menlo, monospace',
            headSize: '9px', bodySize: '11px', headCase: 'uppercase', headTracking: '0.06em',
        },
        glyph: { section: '▮', sectionAlt: '▯', bullet: '▸', sep: ' ', chevron: '▼' },
    },
    {
        slug: 'miami-deco',
        name: 'Miami Deco',
        family: 'retro',
        mode: 'light',
        blurb: 'Deco triple-rules in teal, coral and sand.',
        surface: {
            headFrom: '#f7f2e7', headTo: '#ffd9c9',
            bodyFrom: '#fffdf8', bodyTo: '#f9f4ea',
            row: '#fffefb', rowAlt: '#f2e7d8', inset: '#fbf7ef', chip: '#f7f1e5',
        },
        ink: {
            head: '#0f6b6b', body: '#3d3a34', label: '#e26d5a', muted: '#8f8878',
            strong: '#232019', warm: '#e26d5a', cool: '#0f6b6b',
        },
        line: { head: '#0f6b6b', body: '#e0d6c0', width: '1px', edge: '3px' },
        shadow: { head: 'none', body: 'none' },
        accents: ['#0f6b6b', '#e26d5a', '#e8c07d', '#3f8f8f', '#c94f3d', '#7fb0a8', '#a8834f'],
        radius: { head: '2px', body: '2px', row: '2px', slot: '2px', pill: '2px', chip: '2px' },
        type: {
            family: '"Poiret One", "Century Gothic", ui-sans-serif, sans-serif',
            bodyFamily: 'inherit', headSize: '12px',
            headCase: 'uppercase', headTracking: '0.2em',
        },
        glyph: { section: '▬', sectionAlt: '▭', bullet: '·', sep: '·', chevron: '▾' },
        ornament: { headerBefore: '<span aria-hidden="true" style="display:block;height:5px;margin-bottom:6px;background:repeating-linear-gradient(0deg,#0f6b6b 0 1px,transparent 1px,transparent 2px)"></span>' },
    },
    {
        slug: 'candy-gloss',
        name: 'Candy Gloss',
        family: 'retro',
        mode: 'light',
        blurb: 'High-shine candy gradients with a glossy highlight bar.',
        surface: {
            headFrom: '#ff8fb1', headTo: '#ff5d8f',
            bodyFrom: '#ffffff', bodyTo: '#fff6f9',
            row: '#fffafc', rowAlt: '#ffe9f1', inset: '#fff4f8', chip: '#fff0f6',
        },
        ink: {
            head: '#ffffff', body: '#43323a', label: '#e0447a', muted: '#a4909a',
            strong: '#2c1f25', warm: '#e08b2f', cool: '#2f9fbf',
        },
        line: { head: 'rgba(255,255,255,0.6)', body: '#ffd9e6', width: '1px', edge: '4px' },
        shadow: {
            head: 'inset 0 2px 0 rgba(255,255,255,0.75), 0 8px 18px rgba(224,68,122,0.26)',
            body: '0 6px 14px rgba(224,68,122,0.10)',
        },
        accents: ['#ff5d8f', '#4fc3f7', '#ffd54f', '#7ed957', '#b085f5', '#ff8a65', '#26c6da'],
        radius: { head: '14px', body: '14px', row: '999px', slot: '999px' },
        type: { family: '"Nunito", "Segoe UI", system-ui, sans-serif', bodyFamily: 'inherit', headSize: '12px', headWeight: '700' },
        glyph: { section: '●', sectionAlt: '○', bullet: '•', sep: '·', chevron: '⌄' },
    },

    {
        slug: 'paper-minimal',
        name: 'Paper Minimal',
        family: 'print',
        mode: 'light',
        blurb: 'Off-white with grey hairlines. Hierarchy from weight and space alone.',
        surface: {
            headFrom: '#fbfbf9', headTo: '#f4f4f1',
            bodyFrom: '#ffffff', bodyTo: '#fdfdfc',
            row: '#fafaf8', rowAlt: '#f2f2ee', inset: '#f7f7f5', chip: '#f6f6f3',
        },
        ink: {
            head: '#2c2c2a', body: '#3a3a37', label: '#6b6b66', muted: '#96968f',
            strong: '#1a1a18', warm: '#8a6a3c', cool: '#3f6b78',
        },
        line: { head: '#e2e2dd', body: '#ecece7', width: '1px', edge: '2px' },
        shadow: { head: 'none', body: 'none' },
        accents: ['#4a6fa5', '#6b6b66', '#8a6a3c', '#3f7a6b', '#8a5a70', '#5a6b8a', '#7a7a72'],
        radius: { head: '4px', body: '4px', row: '4px', slot: '4px' },
        space: { bodyPad: '14px', rowPadY: '8px', rowPadX: '10px', gap: '10px' },
        type: {
            family: '"Inter", "Helvetica Neue", system-ui, sans-serif',
            bodyFamily: 'inherit', headSize: '12px', labelCase: 'uppercase', labelSize: '9px',
        },
        glyph: { section: '', sectionAlt: '', bullet: '·', sep: '—', chevron: '▾' },
    },
    {
        slug: 'newsprint',
        name: 'Newsprint',
        family: 'print',
        mode: 'light',
        blurb: 'Halftone cream with black rules and one red spot colour.',
        surface: {
            headFrom: '#f2ece1', headTo: '#e6ddcd',
            bodyFrom: '#f7f2e8', bodyTo: '#f2ece1',
            row: '#fbf8f1', rowAlt: '#efe6d6', inset: '#f6f1e6', chip: '#f2ece1',
        },
        ink: {
            head: '#141414', body: '#1f1f1d', label: '#b22222', muted: '#6e6a60',
            strong: '#000000', warm: '#b22222', cool: '#2f4f6f',
        },
        line: { head: '#141414', body: '#c9c0ad', width: '1px', edge: '0', edgeSide: 'top' },
        shadow: { head: 'none', body: 'none' },
        accents: ['#b22222', '#141414', '#4a4a45', '#2f4f6f', '#7a6a4a', '#8a2a2a', '#3a3a35'],
        radius: { head: '0', body: '0', row: '0', slot: '0', pill: '0', chip: '0' },
        frame: 'halftone',
        type: {
            family: '"Playfair Display", Georgia, "Times New Roman", serif',
            bodyFamily: 'Georgia, "Times New Roman", serif',
            headSize: '13px', headWeight: '700', headCase: 'uppercase', headTracking: '0.06em',
            labelCase: 'uppercase', labelSize: '9px',
        },
        glyph: { section: '', sectionAlt: '', bullet: '·', sep: '|', chevron: '▾' },
        css: '[data-rat-part="row-label"],[data-rat-part="section-label"]{border-bottom:1px solid #141414;padding-bottom:2px}',
    },
    {
        slug: 'ink-vellum',
        name: 'Ink & Vellum',
        family: 'print',
        mode: 'light',
        blurb: 'Warm vellum and dense ink with double hairline rules.',
        surface: {
            headFrom: '#f6f0e2', headTo: '#ece3cf',
            bodyFrom: '#fbf7ec', bodyTo: '#f6f0e2',
            row: '#fdfaf3', rowAlt: '#f0e8d6', inset: '#f8f4e9', chip: '#f4eede',
        },
        ink: {
            head: '#1b1a17', body: '#26241f', label: '#5b4a2f', muted: '#7d7663',
            strong: '#000000', warm: '#8a5a2a', cool: '#2f5a5a',
        },
        line: { head: '#8a7f68', body: '#d6cdb6', width: '1px', edge: '2px' },
        shadow: { head: 'none', body: 'none' },
        accents: ['#5b4a2f', '#7a5c3a', '#3f5a4a', '#6a4a5a', '#8a6a3a', '#4a5a6a', '#3a3428'],
        radius: { head: '2px', body: '2px', row: '2px', slot: '2px' },
        type: {
            family: '"EB Garamond", Garamond, Georgia, serif',
            bodyFamily: '"EB Garamond", Garamond, Georgia, serif',
            headSize: '13px', bodySize: '13px', lineHeight: '1.55',
            labelCase: 'uppercase', labelSize: '9px', headTracking: '0.04em',
        },
        glyph: { section: '', sectionAlt: '', bullet: '·', sep: '·', chevron: '▾' },
        extra: { header: 'border-top:3px double #8a7f68;border-bottom:1px solid #8a7f68' },
    },
    {
        slug: 'editorial-hairline',
        name: 'Editorial Hairline',
        family: 'print',
        mode: 'light',
        blurb: 'No boxes at all. Rules and spacing carry the whole hierarchy.',
        surface: {
            headFrom: '#ffffff', headTo: '#ffffff',
            bodyFrom: '#ffffff', bodyTo: '#ffffff',
            row: 'transparent', rowAlt: '#f7f7f7', inset: '#fafafa', chip: '#f7f7f7',
        },
        ink: {
            head: '#111111', body: '#2a2a2a', label: '#8a8a8a', muted: '#a8a8a8',
            strong: '#000000', warm: '#8a5a2a', cool: '#2a5a7a',
        },
        line: { head: '#111111', body: 'transparent', width: '0', edge: '0', edgeSide: 'none' },
        shadow: { head: 'none', body: 'none' },
        accents: ['#111111', '#c8102e', '#2a5a7a', '#5a5a5a', '#8a5a2a', '#3a6b4a', '#6a4a7a'],
        radius: { head: '0', body: '0', row: '0', slot: '0', pill: '0', chip: '0' },
        space: { headPadY: '6px', headPadX: '0', bodyPad: '4px 0 12px', rowPadY: '7px', rowPadX: '0', gap: '8px' },
        type: {
            family: '"Inter", "Helvetica Neue", system-ui, sans-serif',
            bodyFamily: 'inherit', headSize: '11px', lineHeight: '1.5',
            headCase: 'uppercase', headTracking: '0.16em', headWeight: '700',
            labelCase: 'uppercase', labelSize: '9px',
        },
        glyph: { section: '', sectionAlt: '', bullet: '·', sep: '·', chevron: '▾' },
        extra: { header: 'border-bottom:2px solid #111111', row: 'border-bottom:1px solid #ececec' },
    },
    {
        slug: 'blueprint',
        name: 'Blueprint',
        family: 'print',
        mode: 'dark',
        blurb: 'Technical drawing: cyan on navy, dashed guides, drafting grid.',
        surface: {
            headFrom: '#0e1f33', headTo: '#12263f',
            bodyFrom: '#0b1a2b', bodyTo: '#0e1f33',
            row: 'rgba(120,200,255,0.05)', rowAlt: 'rgba(120,200,255,0.12)',
            inset: 'rgba(120,200,255,0.08)', chip: 'rgba(120,200,255,0.10)',
        },
        ink: {
            head: '#9fd8ff', body: '#dceaf5', label: '#78c8ff', muted: '#6a8ba8',
            strong: '#ffffff', warm: '#ffd08a', cool: '#78c8ff',
        },
        line: { head: 'rgba(120,200,255,0.45)', body: 'rgba(120,200,255,0.22)', width: '1px', style: 'dashed', edge: '2px' },
        shadow: { head: 'none', body: 'none' },
        accents: ['#78c8ff', '#9fd8ff', '#5fa8d8', '#c0e4ff', '#4a90c0', '#8ac0e0', '#ffd08a'],
        radius: { head: '0', body: '0', row: '0', slot: '0', pill: '0', chip: '0' },
        frame: 'ticks',
        type: {
            family: 'ui-monospace, "SF Mono", Menlo, monospace',
            bodyFamily: 'ui-monospace, "SF Mono", Menlo, monospace',
            headSize: '10px', headCase: 'uppercase', headTracking: '0.14em', labelCase: 'uppercase',
        },
        glyph: { section: '+', sectionAlt: '×', bullet: '·', sep: '·', chevron: '▾' },
        extra: { body: 'background-image:repeating-linear-gradient(0deg,rgba(120,200,255,0.06) 0 1px,transparent 1px,transparent 12px),repeating-linear-gradient(90deg,rgba(120,200,255,0.06) 0 1px,transparent 1px,transparent 12px)' },
    },
    {
        slug: 'nordic-frost',
        name: 'Nordic Frost',
        family: 'print',
        mode: 'dark',
        blurb: 'Low-contrast slate. The quietest theme in the pack.',
        surface: {
            headFrom: '#2e3440', headTo: '#3b4252',
            bodyFrom: '#2b3140', bodyTo: '#323947',
            row: 'rgba(216,222,233,0.05)', rowAlt: 'rgba(136,192,208,0.12)',
            inset: 'rgba(216,222,233,0.08)', chip: 'rgba(136,192,208,0.14)',
        },
        ink: {
            head: '#eceff4', body: '#d8dee9', label: '#88c0d0', muted: '#7b8494',
            strong: '#ffffff', warm: '#ebcb8b', cool: '#88c0d0',
        },
        line: { head: 'rgba(136,192,208,0.32)', body: 'rgba(216,222,233,0.14)', width: '1px', edge: '3px' },
        shadow: { head: '0 6px 16px rgba(0,0,0,0.22)', body: 'none' },
        accents: ['#88c0d0', '#81a1c1', '#a3be8c', '#ebcb8b', '#b48ead', '#d08770', '#8fbcbb'],
        radius: { head: '8px', body: '8px', row: '6px', slot: '6px' },
        type: { family: '"Inter", system-ui, sans-serif', bodyFamily: 'inherit', headSize: '11px' },
        glyph: { section: '▪', sectionAlt: '▫', bullet: '·', sep: '·', chevron: '▾' },
    },
];
