/**
 * Regenerates src/stock.js from a SillyBunny checkout.
 *
 * Usage: node scripts/generate-stock.mjs [path-to-SillyBunny]
 *
 * The stock baseline is what "Revert to stock" restores and what drift detection
 * compares against, so it must be byte-identical to what the fork ships.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const fork = process.argv[2] ?? '/home/platinum/SillyBunny';
const templates = join(fork, 'public/scripts/extensions/in-chat-agents/templates');

/** Template files that carry their own `regexScripts` array, outside regex-bundles.json. */
const COMPANION_FILES = [
    'chat-only-companion.json',
    'chatroom-companion.json',
    'message-inbox-companion.json',
];

/** Mirrors public/scripts/utils.js regexFromString so group counts match runtime behaviour. */
function regexFromString(input) {
    try {
        const m = String(input).match(/(\/?)(.+)\1([a-z]*)/i);
        if (m[3] && !/^(?!.*?(.).*?\1)[gmixXsuUAJ]+$/.test(m[3])) {
            return new RegExp(input);
        }
        return new RegExp(m[2], m[3]);
    } catch {
        return null;
    }
}

/** Capture-group count of a compiled regex, via the empty-alternative trick. */
function countGroups(regex) {
    if (!regex) {
        return 0;
    }
    try {
        return new RegExp(`${regex.source}|`).exec('').length - 1;
    } catch {
        return 0;
    }
}

function readJson(path) {
    return JSON.parse(readFileSync(path, 'utf8'));
}

function collect() {
    const out = [];
    const bundles = readJson(join(templates, 'regex-bundles.json'));

    for (const [templateId, scripts] of Object.entries(bundles)) {
        for (const script of scripts) {
            out.push(entry(templateId, script, 'tracker', 'regex-bundles.json'));
        }
    }

    for (const file of COMPANION_FILES) {
        const template = readJson(join(templates, file));
        for (const script of template.regexScripts ?? []) {
            out.push(entry(template.id, script, 'companion', file));
        }
    }

    return out;
}

function entry(templateId, script, family, source) {
    const compiled = regexFromString(script.findRegex);
    return {
        templateId,
        scriptId: script.id,
        scriptName: script.scriptName,
        family,
        source,
        findRegex: script.findRegex,
        groups: countGroups(compiled),
        flags: compiled ? compiled.flags : '',
        delimited: /^\/[\s\S]*\/[a-z]*$/.test(script.findRegex),
        replaceString: script.replaceString ?? '',
        placement: script.placement ?? [2],
        markdownOnly: Boolean(script.markdownOnly),
        promptOnly: Boolean(script.promptOnly),
        minDepth: script.minDepth ?? null,
        maxDepth: script.maxDepth ?? null,
    };
}

const entries = collect();

const header = `/**
 * GENERATED by scripts/generate-stock.mjs. Do not edit by hand.
 *
 * The stock \`replaceString\` of every bundled In-Chat Agent regex script, plus the
 * \`findRegex\` and capture-group count each theme must honour. Used to revert, to
 * detect drift after a template update, and to validate specs in the test suite.
 */

`;

const body = `export const STOCK = ${JSON.stringify(entries, null, 4)};

/** @type {Map<string, typeof STOCK[number]>} keyed \`templateId/scriptId\`. */
export const STOCK_BY_KEY = new Map(STOCK.map(item => [\`\${item.templateId}/\${item.scriptId}\`, item]));

/** Every stock replaceString, for byte-identical drift classification. */
export const STOCK_REPLACE_STRINGS = new Set(STOCK.map(item => item.replaceString));

export function stockKey(templateId, scriptId) {
    return \`\${templateId}/\${scriptId}\`;
}

export function getStock(templateId, scriptId) {
    return STOCK_BY_KEY.get(stockKey(templateId, scriptId)) ?? null;
}
`;

writeFileSync(join(here, '../src/stock.js'), header + body, 'utf8');

const withMarkup = entries.filter(item => item.replaceString).length;
console.log(`stock.js: ${entries.length} scripts (${withMarkup} with markup, ${entries.length - withMarkup} empty)`);
for (const item of entries) {
    const mark = item.replaceString ? ' ' : '·';
    console.log(`${mark} ${item.templateId.padEnd(32)} g=${String(item.groups).padStart(2)} f=${item.flags.padEnd(3)} ${item.delimited ? ' ' : '!'} ${item.scriptName}`);
}
